# -*- coding: utf-8 -*-
"""Doreen Scrape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHyCBjGWgWb2rVdVoE39EyQAqd7-DqQw
"""

import pandas as pd
import requests
import csv
from bs4 import BeautifulSoup

url = 'https://gh.bmj.com/search/malawi%252Bhealth%252Barticles%20jcode%3Abmjgh'

response = requests.get(url)
soup = BeautifulSoup(response.text,'lxml')

results = soup.find_all('div', class_='highwire-cite highwire-cite-highwire-article highwire-citation-bmjj-standard clearfix')
#print(results)

for result in results:
    title = result.find('span', class_='highwire-cite-title')
    journal = result.find('span', class_='highwire-cite-metadata-journal highwire-cite-metadata')

    aurthors = result.find('div', class_='highwire-cite-authors')
    date = result.find('span', class_='highwire-cite-metadata-date highwire-cite-metadata')
    link = result.find('span', class_='highwire-cite-metadata-doi highwire-cite-metadata')
    print(f"Title:{title.text}")
    print(f"Journal of Publication:{journal.text}")
    print(f"Authors: {aurthors.text}")
    print(f"Year:{date.text}")
    print(f"Doi and Link:{link.text}")

from csv import writer
with open('MedicalJournal.csv', 'w', newline='', encoding = 'utf8') as f:
 thewriter = writer(f)
 header = ['Title', 'Journal of Publication', 'Authors', 'Year', 'Doi and Link']
 thewriter.writerow(header)

 for result in results:
    title = result.find('span', class_='highwire-cite-title').text.replace('\n','')
    journal = result.find('span', class_='highwire-cite-metadata-journal highwire-cite-metadata').text.replace('\n','')
    aurthors = result.find('div', class_='highwire-cite-authors').text.replace('\n','')
    date = result.find('span', class_='highwire-cite-metadata-date highwire-cite-metadata').text.replace('\n','')
    link = result.find('span', class_='highwire-cite-metadata-doi highwire-cite-metadata').text.replace('\n','')
    journalinfo = [title, journal, aurthors, date, link]
    thewriter.writerow(journalinfo)